const CONSTANTS = {} as any;

CONSTANTS.NOTHING_ACTION = 'NOTHING_ACTION';
CONSTANTS.ACTION_CLEAN_AUTH = 'ACTION_CLEAN_AUTH';
CONSTANTS.ACTION_LOGIN = 'ACTION_LOGIN';
CONSTANTS.POST = 'POST';
CONSTANTS.GET = 'GET';
CONSTANTS.PUT = 'PUT';
CONSTANTS.DELETE = 'DELETE';
CONSTANTS.ACTION_CLEAN_PUBLICATIONS = 'ACTION_CLEAN_PUBLICATIONS';
CONSTANTS.PUBLICATIONS_GET = 'PUBLICATIONS_GET';
CONSTANTS.PUBLICATIONS_POST = 'PUBLICATIONS_POST';
CONSTANTS.PUBLICATIONS_GET_ONE = 'PUBLICATIONS_GET_ONE';
CONSTANTS.PUBLICATIONS_UPDATE_ONE = 'PUBLICATIONS_UPDATE_ONE';
CONSTANTS.PUBLICATIONS_DELETE = 'PUBLICATIONS_DELETE';

export default CONSTANTS;