const CONSTANTS = {} as any;

CONSTANTS.NOTHING_ACTION = 'NOTHING_ACTION';
CONSTANTS.ACTION_CLEAN_AUTH = 'ACTION_CLEAN_AUTH';
CONSTANTS.ACTION_LOGIN = 'ACTION_LOGIN';
CONSTANTS.POST = 'POST';
CONSTANTS.GET = 'GET';
CONSTANTS.ACTION_CLEAN_PUBLICATIONS = 'ACTION_CLEAN_PUBLICATIONS';
CONSTANTS.PUBLICATIONS_GET = 'PUBLICATIONS_GET';

export default CONSTANTS;