const CONSTANTS = {} as any;

CONSTANTS.NOTHING_ACTION = 'NOTHING_ACTION';
CONSTANTS.ACTION_CLEAN_AUTH = 'ACTION_CLEAN_AUTH';
CONSTANTS.ACTION_LOGIN = 'ACTION_LOGIN';
CONSTANTS.POST = 'POST';

export default CONSTANTS;